### PR TITLE
Documentation how to import the deck into anki

### PR DESCRIPTION
**Pull request by baerrach**
Upgraded to export *all* headers.
The header types are a merge from all the export capabilities.
Added documentation on how to import into Anki, with detailed instructions to setup the deck and card types.

Both this and the Anki gem dependency are not minor patches - they should really have their versions bumped better to sit with http://semver.org/ I'll let you decide that.

Also I'm hacking at this ruby/padrino/bootstrap stuff so I may not have done things correctly (but it works!)
I'd like to add a bootstrap navbar but I dont have time at the moment. The link_tos work for now.

### CODE REVIEW

**Comment by dennmart** [comment]
The tests for this branch are failing for me :crying_cat_face:

**Comment by baerrach** [comment]
Is everything good to go now?
Do you need any more information from me?

**Comment by dennmart** [comment]
Ah, I didn't realize you updated this pull request. I'll check it out later tonight or tomorrow and if it's all good, I'll merge and deploy it to the site. Thanks again!

**Comment by baerrach** [comment]
On 5 February 2015 at 09:48, Dennis Martinez <notifications@github.com>
wrote:

> Ah, I didn't realize you updated this pull request. I'll check it out
> later tonight or tomorrow and if it's all good, I'll merge and deploy it to
> the site. Thanks again!\
>

No worries!
That's the benefit of open source.

I had an itch that needed scratching - so I scratched it.
Now I've got an Anki deck that looks good, rolls all the WaniKani exports
into one deck and instructions that others can also follow.

I'd really like to cleanup the navbar code but I'm no Bootstrap expert.
I have a feeling that should also be DRY'ed up across the various pages.

And one day, if there are more docs, work out how to automatically create
the Table of Contents...

**Comment by dennmart** [comment]
Sorry it took me a while to get to this. Thanks so much for writing those docs and adding all that functionality!

**Pull request merged**
